name: fsra_pytorch18
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.8

  # PyTorch ecosystem for CUDA 10.2
  - pytorch=1.8.0
  - torchvision=0.9.0
  - cudatoolkit=10.2

  # Core scientific computing
  - numpy=1.21.*
  - scipy=1.7.*
  - matplotlib=3.5.*
  - pillow=8.*

  # Configuration and utilities
  - pyyaml=5.*
  - tqdm

  # Development tools
  - jupyter
  - ipython

  # Additional dependencies via pip
  - pip
  - pip:
    - tensorboard>=2.4.0,<3.0.0
    - opencv-python>=4.5.0,<5.0.0
    - scikit-learn>=0.24.0,<1.1.0
    - pytest>=6.0.0
    - flake8>=3.8.0
    - black>=21.0.0
